version: '3'

services:
  client:
    build:
      context: ../client
      dockerfile: ./Dockerfile
    environment:
      CLIENT_PORT: ${CLIENT_PORT}
      SERVER_HTTP_PORT: ${SERVER_HTTP_PORT}
      SERVER_HOST: server
    networks:
      smonitor:
        aliases:
          - client
    ports:
      - '${CLIENT_PORT}:${CLIENT_PORT}'
  server:
    build:
      context: ..
      dockerfile: ./Dockerfile
    environment:
      GRPC_PORT: ${SERVER_GRPC_PORT}
      HTTP_PORT: ${SERVER_HTTP_PORT}
      TICK_INTERVAL: ${TICK_INTERVAL}
      MAX_MEASURE_INTERVAL: ${MAX_MEASURE_INTERVAL}
      PARSERS: ${PARSERS}
      LOG_LEVEL: ${LOG_LEVEL}
      PRODUCTION: ${PRODUCTION}
    networks:
      smonitor:
        aliases:
          - server

networks:
  smonitor:
    driver: bridge
